# Schema
"$schema" = 'https://starship.rs/config-schema.json'

# Basic
format = "$directory$git_branch$git_status$character" 
right_format = "$time"
add_newline = false
command_timeout = 1000

# makes prompt a single line
[line_break]
disabled = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
format = "$symbol "
success_symbol = "[>](green)"
error_symbol = "[>](red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Directory
[directory]
style = "bold cyan"
truncate_to_repo = true
truncation_length = 1
fish_style_pwd_dir_length = 1

# Time
[time]
disabled = false
format = "[$time]($style)"
style = "bright-cyan"
time_format = "%H:%M:%S"

# Git
[git_branch]
format = "([\\($branch]($style))"
style = "bold purple"

[git_status]
format = "[$all_status[\\)](bold purple)]($style)"
style = "red"
